"""unique constraint

Revision ID: bdbfd135d836
Revises: dcd0469ead6f
Create Date: 2022-09-20 17:00:25.378920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbfd135d836'
down_revision = 'dcd0469ead6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reserv_ref_id', table_name='reserv')
    op.create_index(op.f('ix_reserv_ref_id'), 'reserv', ['ref_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserv_ref_id'), table_name='reserv')
    op.create_index('ix_reserv_ref_id', 'reserv', ['ref_id'], unique=False)
    # ### end Alembic commands ###
