"""hotel model

Revision ID: dcd0469ead6f
Revises: f401e9b6d79d
Create Date: 2022-09-20 16:08:13.962043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd0469ead6f'
down_revision = 'f401e9b6d79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_column('hotel', 'hotel_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('hotel_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('hotel', 'name')
    # ### end Alembic commands ###
