"""updated mapping

Revision ID: dfade2c9790b
Revises: 17e7d635da46
Create Date: 2022-09-22 16:19:49.495557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfade2c9790b'
down_revision = '17e7d635da46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hotel_mapping', 'hotel', ['mpae_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_mapping', type_='foreignkey')
    # ### end Alembic commands ###
